Provide a way to specify the version of the ingress helm chart
kube-hetzner/terraform-hcloud-kube-hetzner pull request #1123
Opened 2023-12-13 23:08 UTC by mnencia

With these two new options, you can control the helm chart version for traefik and nginx ingresses.

2023-12-14 01:09 UTC, mysticaltech requested changes
@mnencia  So good seeing your PRs again! Just a few comments. Maybe some changes were not committed on your end.

2023-12-14 01:09 UTC, mysticaltech commented on init.tf
> +      coalesce(var.nginx_chart_version, "N/A"),
Could we remove the _chart_ so that the naming becomes consistant with the other ones like cilium_version?

2023-12-14 01:09 UTC, mysticaltech commented on templates/nginx_ingress.yaml.tpl
> +  name: ${target_namespace}
I do not see the logic that determines the value of `target_namespace`. Where is it?

2023-12-14 01:09 UTC, mysticaltech commented on templates/nginx_ingress.yaml.tpl
> +  version: "${version}"
Here also, I'm not seeing the value that determines the value of `version` and fetches the latest if empty. Maybe I'm missing something.

2023-12-14 07:42 UTC, mnencia commented on init.tf
> +      coalesce(var.nginx_chart_version, "N/A"),
We can, but what you specify here is the chart version that in general is different from the software version. If you think it's better to remove the chart word I'll do it

2023-12-14 07:43 UTC, mnencia commented on templates/nginx_ingress.yaml.tpl
> +  version: "${version}"
If you do not specify anything you revert to the previous behavior, and you select the latest at the moment of the installation

2023-12-14 07:48 UTC, mnencia commented on templates/nginx_ingress.yaml.tpl
> +  name: ${target_namespace}
The value is already used in the chart below. It is passed to the template from the local.ingress_namespace variable. See init.tf file.

2023-12-14 16:48 UTC, mysticaltech commented on init.tf
> +      coalesce(var.nginx_chart_version, "N/A"),
@mnencia Ah I understand now, the chart version does not correspond to the software version, so all is good. Thanks for the clarification!

2023-12-14 16:48 UTC, mysticaltech commented on templates/nginx_ingress.yaml.tpl
> +  name: ${target_namespace}
Ah yes, my bad. Awesome!

2023-12-14 16:49 UTC, mysticaltech commented on templates/nginx_ingress.yaml.tpl
> +  version: "${version}"
Ok, wonderful!

2023-12-14 16:51 UTC, mysticaltech commented on init.tf
> +      coalesce(var.nginx_chart_version, "N/A"),
I see you made the change, since it's not used anywhere else I think we can keep it like with without _chart_, just for consistancy. Thanks!

2023-12-14 16:51 UTC, mysticaltech approved these changes
LGTM  🚀

2023-12-14 17:25 UTC, aleksasiriski approved these changes
I've literally wanted to add these for the past couple of days, with #1126 as well

2023-12-15 13:01 UTC, merged

2024-01-07 06:28 UTC, mysticaltech commented
@mnencia  FYI, please join us on discord https://discord.gg/VcSYQp7D