Allow empty agent_nodepools
kube-hetzner/terraform-hcloud-kube-hetzner pull request #1169
Opened 2024-01-12 00:09 UTC by vilaca

When declaring an empty agent_nodepools list an error was thrown.

```
│ Error: Invalid function argument
│
│   on ../terraform-hcloud-kube-hetzner/locals.tf line 167, in locals:
│  167:   agent_count            = sum([for v in var.agent_nodepools : v.count])
│     ├────────────────
│     │ while calling sum(list)
│     │ var.agent_nodepools is empty list of object
│
│ Invalid value for "list" parameter: cannot sum an empty list.
```

Replacing sum w/ list fixes the issue.

2024-01-12 11:24 UTC, mnencia requested changes

2024-01-12 11:24 UTC, mnencia commented on locals.tf
> +  agent_count            = length(var.agent_nodepools)
That's not correct. The original code counts the number of agents across all the agent node pools. The new code counts the number of agent node pools.

2024-01-16 13:54 UTC, mysticaltech commented
@vilaca Sorry about that. Please read our docs well, and post an issue with details on how to reproduce if it fails for you. This is not a correct fix.

2024-01-16 13:54 UTC, closed without merging

2024-01-16 14:27 UTC, vilaca commented
> @vilaca Sorry about that. Please read our docs well, and post an issue with details on how to reproduce if it fails for you. This is not a correct fix.

I'll try to post a correct PR next weekend or when possible.