sepolicy changes for fluentbit
kube-hetzner/terraform-hcloud-kube-hetzner pull request #1288
Opened 2024-03-19 08:08 UTC by patope

There policy changes are need to make fluentbit to work on cluster

2024-03-19 14:48 UTC, mysticaltech requested changes

2024-03-19 14:48 UTC, mysticaltech commented on locals.tf
> +    allow container_t var_lib_t:file { create lock open read setattr write getattr unlink };
@patope var_log_t should not be removed.

2024-03-23 09:09 UTC, patope commented on locals.tf
> +    allow container_t var_lib_t:file { create lock open read setattr write getattr unlink };
Now there are 3 separate rows for `var_log_t:dir` and `var_log_t:file` permissions

2024-03-26 10:54 UTC, aleksasiriski commented on locals.tf
> +    allow container_t var_lib_t:file { create lock open read setattr write getattr unlink };
Why not combine all the perms of the same class into single line? I see that wasn't done in the master branch, but maybe it should? Correct me if I'm wrong.

2024-03-29 10:29 UTC, mysticaltech commented on locals.tf
> +    allow container_t var_lib_t:file { create lock open read setattr write getattr unlink };
I want to do that too, will fix.

2024-03-29 10:29 UTC, mysticaltech approved these changes
Thanks for this @patope, and sorry for the delay, was a busy week. Merging now.

2024-03-29 10:30 UTC, merged