Add recursive user manifests
kube-hetzner/terraform-hcloud-kube-hetzner pull request #1314
Opened 2024-04-08 17:01 UTC by markusheinemann

see #1313 

# How to Test

1. Create the following files inside of `extra-manifests`:

#### **`kustomization.yaml.tpl`**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - subfolder
```

#### **`subfolder/kustomization.yaml.tpl`**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
```

#### **`subfolder/namespace.yaml.tpl`**

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
```

2. Create a cluster using `terrafom apply`

3. Check if the resource has been applied: `kubectl get ns`

2024-04-09 02:06 UTC, mysticaltech requested changes
@markusheinemann Thanks for this. Looking good. Please if you could tweak the docs for this, especially in the examples section in the readme and other relevant places (if this is mentioned there, like kube.tf), it would be great.

2024-04-09 07:21 UTC, markusheinemann commented
> @markusheinemann Thanks for this. Looking good. Please if you could tweak the docs for this, especially in the examples section in the readme and other relevant places (if this is mentioned there, like kube.tf), it would be great.

I have updated the related docs and updated the examples as well. I am happy about your feedback.

2024-04-11 09:20 UTC, markusheinemann commented
Actual the provided solution will not work due to https://github.com/hashicorp/terraform/issues/16330

2024-04-11 09:42 UTC, markusheinemann commented on kustomization_user.tf
>  resource "null_resource" "kustomization_user" {
Possible solution to solve the terraform file provisioner is to create the directories before copying

```
  provisioner "remote-exec" {
    inline = [
      "mkdir -p $(dirname /var/user_kustomize/${each.key})"
    ]
  }
```

2024-04-12 14:05 UTC, mysticaltech approved these changes
Awesome @markusheinemann! Please let me know when it's working.

2024-05-01 08:02 UTC, mysticaltech commented
@markusheinemann What about now?

2024-05-02 08:01 UTC, markusheinemann commented
lgtm. I think the PR is done 💯

2024-05-02 08:08 UTC, markusheinemann commented
lgtm. I think the PR can be merged in my eyes. Can you please rerun the workflow?

PS. Sorry for closing the PR due to an oversight

2024-05-21 17:07 UTC, merged