Fix swap creation issue
kube-hetzner/terraform-hcloud-kube-hetzner pull request #1402
Opened 2024-07-09 07:18 UTC by olexiyb

wrap swap creation with transactional-update --continue shell to fix the issue of missing swap after node reboot fix for https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/1399

2024-07-24 09:10 UTC, mysticaltech requested changes
@olexiyb Looking good, just one tiny change, and please also confirm that this is well tested and the swap on activation service works.

2024-07-24 09:10 UTC, mysticaltech commented on modules/host/templates/cloudinit.yaml.tpl
> +# I use separate systemd script
If you can move those commants to the PR itself it woudl be great please. Best to not have comments in cloudinit. If you want to point to the permalink of your PR comment with this info in code comment, that would be best to satisfy the curiosity of some.

2024-07-27 07:21 UTC, olexiyb commented on modules/host/templates/cloudinit.yaml.tpl
> +# I use separate systemd script
emoved comments. Yes I currently running 3 clusters, each has 3 control panels with swap
Here is some captured data from one of my nodes

```
scmain-s1-zdx:/ # journalctl | grep swapon
Jul 15 06:33:05 scmain-s1-zdx cloud-init[1094]: Created symlink /etc/systemd/system/default.target.wants/swapon-late.service → /etc/systemd/system/swapon-late.service.
Jul 15 06:49:08 scmain-s1-zdx swapon[617]: swapon: /var/lib/swap/swapfile: swapon failed: Read-only file system
Jul 15 06:49:24 scmain-s1-zdx systemd[1]: swapon-late.service: Deactivated successfully.
Jul 25 01:16:12 scmain-s1-zdx swapon[616]: swapon: /var/lib/swap/swapfile: swapon failed: Read-only file system
Jul 25 01:16:32 scmain-s1-zdx systemd[1]: swapon-late.service: Deactivated successfully.
scmain-s1-zdx:/ # swapon
NAME                   TYPE SIZE USED PRIO
/var/lib/swap/swapfile file   8G 2.5M   -2
scmain-s1-zdx:/ # free -h
               total        used        free      shared  buff/cache   available
Mem:           3.7Gi       1.8Gi        82Mi        18Mi       2.0Gi       1.9Gi
Swap:          8.0Gi       2.0Mi       8.0Gi
```

Without swap I had to buy bigger node for control plan to run it stable. I have in total 3 clusters with 3 control nodes. So I am saving around 2.8 euros on each node.

2024-08-09 01:24 UTC, mysticaltech approved these changes
Awesome! Thanks @olexiyb

2024-08-09 01:25 UTC, merged