Add calico as alternative CNI
kube-hetzner/terraform-hcloud-kube-hetzner pull request #141
Opened 2022-04-02 21:04 UTC by nupplaphil

Because I want to use Istio with the cluster, based on this repo, I now added the possibility to use calico too.

I tried at least these connection tests:
- https://projectcalico.docs.tigera.io/security/tutorials/kubernetes-policy-basic
- https://projectcalico.docs.tigera.io/security/tutorials/kubernetes-policy-advanced

Based on the suggestions at #137 

And all steps went fine without any error

2022-04-05 11:11 UTC, mysticaltech commented
Hey @nupplaphil, thank you for this PR! Looking forward to the few tweaks above. and being able to merge them.

2022-04-08 18:18 UTC, nupplaphil commented
@mysticaltech - from my point of view, the PR was done already, do you see any troubles merging it?
tbh I didn't thought about adding cilium as well because I don't need it (yet).

2022-04-08 18:25 UTC, mysticaltech commented
Cilium is not the problem here @nupplaphil. There are issues in this PR, see my comments above. When these are addressed then definitely I will be happy to merge.

2022-04-08 18:29 UTC, nupplaphil commented
tbh - did you really send your review? I don't see any comments

2022-04-08 21:19 UTC, mysticaltech requested changes

2022-04-08 21:21 UTC, mysticaltech commented
> tbh - did you really send your review? I don't see any comments

Apologies, indeed I had not submitted my reviews!  You guessed right 🙏

2022-04-08 21:22 UTC, mysticaltech commented on control_planes.tf
> +        flannel-iface = "eth1"
Here talking about line 59.

2022-04-09 18:22 UTC, nupplaphil commented
OK, back to draft, I had a strange flexvolume error, I'll investigate it first

2022-04-09 21:36 UTC, mysticaltech commented
Don't forget to do the changes I suggested. Could solve your problem, especially the eth1.

2022-04-09 22:45 UTC, nupplaphil commented
I already changed it, but a pod of a test nginx throws a strange Felix driver (uds) not found exception. I guess I have to check the paths :)

But thanks for the suggestion :)

2022-04-10 19:45 UTC, nupplaphil commented
Now it works.

We now set the "volume-plugin-dir" to `/var/lib/kubelet/volumeplugins` independent if we use calico, because the default directory would be set to `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/`, which is wrong for the whole setup (=> `/usr` is readonly). 

It's now working for istio as well (successfully set mTLS per calico & cert-manager for pods inside the istio mesh)

2022-04-11 09:07 UTC, mysticaltech commented
Amazing, good find @nupplaphil!

2022-04-11 09:11 UTC, mysticaltech approved these changes

2022-04-11 09:13 UTC, mysticaltech commented
I will just run one deploy, ASAP this week, and if all checks out, will merge.

2022-04-13 14:03 UTC, merged

2022-04-14 11:40 UTC, mysticaltech commented
Hey @nupplaphil, it would be an honor for us to have you join Kube Hetzner (I have just invited you on Github). If you accept, you will become a member of our team and have access to branches, issues... etc. And help steer the future of this project.

And here's an invitation to our private chat room on Matrix (I use the element.io client) [nupplaphil](https://matrix.to/#/#kube-hetzner:matrix.org) (will delete later)! :)

2022-04-14 18:35 UTC, nupplaphil commented
Hi  @mysticaltech , thanks for your invitation! I'll happily accept it, but I'm not sure, how much time I can offer to support this project. I'll do my best :-)

I'm currently setting up my Matrix homeserver and will join the group as soon as possible

2022-04-14 19:49 UTC, mysticaltech commented
Welcome, welcome! 🙏 Don't worry about time if you see the others; some do not show for weeks! 😂

All are just voluntary contributions; we're like a distributed system! When someone has an idea to move the project forward, they chip in. Nothing more!

Very happy that you are deploying your Matrix server! Last time, matrix.org was not working amazingly, probably it was overloaded or something. So great idea! See you on the other side! :) 

Please do copy the link, to join above, then give a thumb up, and I will delete all these messages as not related to the PR.