added autogen of terraform docs
kube-hetzner/terraform-hcloud-kube-hetzner pull request #205
Opened 2022-05-25 19:20 UTC by batthebee

2022-05-25 19:35 UTC, batthebee commented
@strowi can you take a look on this?

2022-05-26 08:55 UTC, nupplaphil requested changes

2022-05-26 08:55 UTC, nupplaphil commented on README.md
> +🌱 This project currently installs openSUSE MicroOS via the Hetzner rescue mode, making things a few minutes slower. If you could **take a few minutes to send a support request to Hetzne, asking them
```suggestion
🌱 This project currently installs openSUSE MicroOS via the Hetzner rescue mode, making things a few minutes slower. If you could **take a few minutes to send a support request to Hetzner, asking them to please add openSUSE MicroOS as a default image**, not just an ISO. The more requests they receive, the likelier they are to add support for it, and if they do, that will cut the deployment time by half. The official link to openSUSE MicroOS is <https://get.opensuse.org/microos>, and their `OpenStack Cloud` image has full support for Cloud-init, which would probably suit the Hetzner Ops team!
```

2022-05-26 08:57 UTC, nupplaphil requested changes

2022-05-26 08:57 UTC, nupplaphil commented on README.md
> +## Reference
This seems redundant/unnecessary

2022-05-26 10:25 UTC, strowi commented
> @strowi can you take a look on this?

Perfect @batthebee should be very helpful to have the variables autogenerated.  ;)

2022-05-26 10:26 UTC, strowi approved these changes

2022-05-26 12:05 UTC, mysticaltech commented on README.md
> +🌱 This project currently installs openSUSE MicroOS via the Hetzner rescue mode, making things a few minutes slower. If you could **take a few minutes to send a support request to Hetzne, asking them
Indeed, good catch, @nupplaphil! 🥳

2022-05-26 12:08 UTC, mysticaltech commented on README.md
> +## Reference
I see what you mean; I would be more for saving this in a new md file.

2022-05-26 12:10 UTC, mysticaltech commented
@batthebee Can we instead save this in a new file? We already have a docs folder with SSH.md in it, maybe we could add Terraform.md, and link to it from the main README.md. I would prefer it that way! Especially if it can be auto-regenerated, it would be even more awesome!

2022-05-27 05:34 UTC, batthebee commented
@mysticaltech do you have a suggestion in which section i should insert the link in the README.md?

2022-05-27 07:11 UTC, mysticaltech commented
@batthebee At the end of "creating your kube.tf" would be ideal! 🙏

2022-05-27 14:08 UTC, mysticaltech commented
@batthebee If you can finish fast, it would be an awesome addition to our upcoming 1.3.0 release that is due when we merge your other PR! 🤞

2022-05-28 23:49 UTC, batthebee commented on README.md
> +🌱 This project currently installs openSUSE MicroOS via the Hetzner rescue mode, making things a few minutes slower. If you could **take a few minutes to send a support request to Hetzne, asking them
Done

2022-05-28 23:49 UTC, batthebee commented on README.md
> +## Reference
Done

2022-05-29 01:40 UTC, nupplaphil approved these changes

2022-05-29 09:08 UTC, mysticaltech approved these changes
Wonderful!

2022-05-29 09:09 UTC, merged