Fix placement groups
kube-hetzner/terraform-hcloud-kube-hetzner pull request #333
Opened 2022-10-02 10:06 UTC by nupplaphil

I'm working with ~20-22 nodes and everytime, I re-created the whole cluster, it failed because of wrong placement_group mappings (it tried to map >10 nodes at one placement_group)

As far as I could calculate, the placement_group logic is starting one ID above 0 (1) and accidentally used the terraform overflow-logic (if n+1 is longer than the array-size, start from 0)

I think I solved it by slightly replace the calculation :-)

2022-10-03 07:28 UTC, mysticaltech requested changes
Glad to see such a decent size cluster being deployed with our tool. Thanks for your suggestion @nupplaphil.

2022-10-03 07:32 UTC, mysticaltech commented on agents.tf
> -  placement_group_id         = var.placement_group_disable ? 0 : element(hcloud_placement_group.agent.*.id, ceil(each.value.index / 10))
There is a +1 issue indeed for the index because we did not consider that it starts at 0. So just doing -1 should fix it, instead of using the floor function!

Please try this, and if good, do submit the changes so we can merge 🙏🏻

placement_group_id   = var.placement_group_disable ? 0 : element(hcloud_placement_group.agent.*.id, ceil(each.value.index / 10) - 1)

2022-10-04 21:57 UTC, mysticaltech commented on agents.tf
> -  placement_group_id         = var.placement_group_disable ? 0 : element(hcloud_placement_group.agent.*.id, ceil(each.value.index / 10))
@nupplaphil, Any updates on this? It is an important fix.

2022-10-04 22:00 UTC, nupplaphil commented
I cannot update this PR before tomorrow evening (in about 20hours), sry :-/

2022-10-04 22:03 UTC, mysticaltech commented
No worries @nupplaphil, thanks good, thanks!!

2022-10-06 15:10 UTC, mysticaltech commented
Am awaiting confirmation to merge and release! Just try the above proposed changes with +20 setup please, and confirm all good! :) Whenever you can...

2022-10-06 19:53 UTC, mysticaltech commented
@nupplaphil What I would like you is test the above. With 20-something nodes, the bill can go up fast! But since you use that already... And it's your PR, I though you could test it.

2022-10-07 04:18 UTC, mysticaltech commented on agents.tf
> -  placement_group_id         = var.placement_group_disable ? 0 : element(hcloud_placement_group.agent.*.id, ceil(each.value.index / 10))
You are right, the floor function works great here! Thanks.

2022-10-07 04:18 UTC, mysticaltech commented
I did a small test, and the floor function works great here, indeed. Thanks for this fix @nupplaphil!

2022-10-07 04:18 UTC, merged