Helm - Replace local `value.yaml` files with variables/locals
kube-hetzner/terraform-hcloud-kube-hetzner pull request #374
Opened 2022-10-26 19:52 UTC by nupplaphil

I'm currently using this repository as a sub-module of my whole cluster-configuration and use the GitOp pattern for it.

Therefore I do think that we shouldn't use local *.yaml files at the root of this repo for configuration, because one must not commit it to this upstream (of course), but on the other hand, we cannot manage these values anywhere else ..

So I created a `*_values` variable for each Helm configuration, we do have so far and adapted the `locals` of them to either use the default setup, or use the content of each `*_values` variable.

For backward compatibility, one can "dump" the current, local file into the corresponding `*_value`, so it shouldn't make any difference.

ToDos:
- [ ] Updating the `README`

2022-10-26 21:23 UTC, mysticaltech commented on variables.tf
> +variable "calico_values" {
@nupplaphil Currently, Calico does not use a helm chart cause I did not find a straightforward one; if you can replace the current manifest with a helm chart, it would be great!

2022-10-26 21:25 UTC, mysticaltech commented
@nupplaphil A lot cleaner, man; I love it! 🙏

2022-10-27 18:14 UTC, mysticaltech commented
@nupplaphil Is the read me the only thing left? Did you test everything?

2022-10-27 18:24 UTC, nupplaphil commented
> @nupplaphil Is the read me the only thing left? Did you test everything?

I successfully used it for creating my environment with a mix of customized values and standard values

2022-10-28 00:08 UTC, mysticaltech commented
@captnCC @WolfspiritM @ifeulner If you could take a quick look it would be awesome! Would love to hear what you think of that one. Personally, I like it, it cleaner.

If all good, I will just complete the readme part myself and we can merge!

2022-10-31 08:58 UTC, ifeulner approved these changes
sorry - was too fast.

2022-10-31 09:33 UTC, ifeulner commented on locals.tf
> +%{if !local.using_klipper_lb~}
Ah I was to fast... this is not the same than the check previously `{ if using_hetzner_lb ~}`
at least for me the lb gets not the right name when using traefik.

2022-10-31 09:34 UTC, ifeulner requested changes
see my comment

2022-10-31 10:23 UTC, nupplaphil commented on locals.tf
> +%{if !local.using_klipper_lb~}
Hmmm Strange I copied exactly the condition, are there currently any traefik issues with the current stable?

2022-10-31 12:34 UTC, mysticaltech commented on locals.tf
> +%{if !local.using_klipper_lb~}
@nupplaphil No there are not any known issues! Good catch @ifeulner.  Philipp, may you just need to pull the latest?!

2022-11-02 16:57 UTC, mysticaltech commented
@nupplaphil This is too good to stay on the shelf just for one line, but I would prefer it came from you, please! 🙏

2022-11-02 18:24 UTC, nupplaphil commented on locals.tf
> +%{if !local.using_klipper_lb~}
But it's effectly the same, see
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/374/files#diff-1366caed88e51e22bcd5a911420820bee3495d781ecccd85f25e00170fc325b8L140
.. I just use the variable instead of the mapped variable ..

2022-11-02 18:48 UTC, nupplaphil commented
I updated the README including some minor fixings inside the README. I'm finished now, except the question about the variable :-/

2022-11-03 14:56 UTC, mysticaltech commented on locals.tf
> +%{if !local.using_klipper_lb~}
Ah yes, it is indeed the same! When you look at the link above @ifeulner, you'll understand. Thanks @nupplaphil!

2022-11-03 14:59 UTC, mysticaltech commented
Awesome @nupplaphil, thanks for that! Will merge and release tonight.

2022-11-04 02:04 UTC, merged

2022-11-04 04:26 UTC, mysticaltech commented
@nupplaphil Turns out  @ifeulner was right, traefik was not deploying, but it was fixed in #392. However, great PR man, thanks again! 🚀✨

2022-11-04 05:11 UTC, mysticaltech commented
Basically, there was two things, the test of equality to `!= null` was replaced by `!= ""`, and the spacing of the yaml object for traefik was wrong, some `~}` were also messing things up (and causing helm to fail), and some comments `# ...` (probably not important that last one).