Added option to configure private registries.
kube-hetzner/terraform-hcloud-kube-hetzner pull request #432
Opened 2022-11-21 23:23 UTC by s3rius

Hi and thanks for amazing project. 

I needed to connect my cluster to existing registries, but I couldn't find an option to do so. 
This is my attempt to create such option.

## Q&A
> Why you don't create this file on node startup?

Because if you change registries.yaml contents later we need to reload all k3s services on all nodes.

> Why do new resources depend on kustomization?

Because otherwise, when we create cluster for the first time and you provide custom registry config, the error may occur.
Since we need to restart k3s services after updating the config.

I would really appreciate a feedback for this PR.

Signed-off-by: Pavel Kirilin <win10@list.ru>

2022-11-22 07:30 UTC, mysticaltech requested changes
@s3rius Looking good to me (just one tiny change requested)! It's tried and tested, correct?

2022-11-22 07:30 UTC, mysticaltech commented on kube.tf.example
> +  # k3s_registries = <<-EOT
@s3rius Here, just to make it consistent with the helm values variables at the bottom of the file, and to remove potential indentation errors from users, can we change this to block comments (instead of line comments)?

2022-11-22 07:43 UTC, s3rius commented on kube.tf.example
> +  # k3s_registries = <<-EOT
Yeah. I tested it, it works as intended.

2022-11-22 07:47 UTC, s3rius commented on kube.tf.example
> +  # k3s_registries = <<-EOT
Ok, I changed comment styles.

2022-11-22 07:50 UTC, s3rius commented
@mysticaltech, sorry, I requested rereview from you and it accidentally removed @ifeulner from reviewers.

2022-11-22 09:24 UTC, mysticaltech approved these changes
Awesome! 🚀

2022-11-23 19:31 UTC, ifeulner commented
Hi @s3rius thanks for contributing  - awesome! Just to get it right - the idea is to add/adjust the registry settings AFTER the cluster has been created, right? And you're restarting the node after applying the new setting. As there is no "drain" before, there will be at least possibilities to corrupt data, I think... 
Also the autoscaler nodes are not getting the new registry setting, this is another problem. 

So another alternative would be to set the registry settings when a node is created, and only then. This setting could also be used when the cloud-init for the autoscaler nodes is prepared.
But no change afterwards possible anymore...  but with the creation of new nodes a new registry setting could also be applied.

So I see some drawbacks with both ways ... what do you think @mysticaltech?

2022-11-23 21:49 UTC, s3rius commented
That's a good take. But reboot is necessary after updating registry.yaml. Also, I'm not sure if it's possible to update autoscaled nodes. Maybe adding it to cloudconfig would be a nice solution. But still, I'm not sure how to drain and reboot nodes after updates.

2022-11-24 06:14 UTC, mysticaltech commented
@ifeulner Right on spot, I completely missed the need for draining. 

But there's an easy way around that issue. @s3rius, just do the exact same thing for the registry file as is done for the k3s config file, which is first created in `/tmp/config.yaml` (see https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/b8dcab2bc7b5fc1a7b16b596364c9ecb4df76274/agents.tf#L52), and then moved to the right k3s folder in   common_commands_install_k3s (see https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/b8dcab2bc7b5fc1a7b16b596364c9ecb4df76274/locals.tf#L14).

That way, registries.yaml will follow the exact same path as config.yaml. And this will work as the [k3s docs](https://docs.k3s.io/installation/private-registry) says that _Upon startup, K3s will check to see if a registries.yaml file exists at /etc/rancher/k3s/ and instruct containerd to use any registries defined in the file._.

2022-11-25 15:36 UTC, mysticaltech commented
@s3rius If you need any help, please let me know, this is normally quite straightforward.

2022-11-26 01:10 UTC, s3rius commented
Thanks for offering help. I'm just chilling. I'll do it next week.

2022-11-29 21:41 UTC, s3rius commented
Hi, everyone. I rewrote this pull request using cloud-config as you told me. It works.

2022-11-29 21:51 UTC, mysticaltech commented
@s3rius Even better! Perfect. @ifeulner Any final comments before we merge?

2022-11-30 08:59 UTC, ifeulner approved these changes
LGTM for now!

2022-12-02 16:48 UTC, merged

2022-12-02 16:52 UTC, mysticaltech commented
Just released, thanks @s3rius!