A few changes - **FIXED CHECK FOR `IP` WHEN USING LB_HOSTNAME**
kube-hetzner/terraform-hcloud-kube-hetzner pull request #523
Opened 2023-01-18 10:30 UTC by aleksasiriski

Of course, you don't have to accept this PR but at least take a look (mainly at fix for lb_hostname).

1. Switched to official helm chart for Longhorn, which doesn't have CRD.
2. Switched to official helm chart for Traefik instead of k3s one, which allows replication with cert-manager.
3. Removed traefik integrated acme since it can't be replicated.
4. Enabled Cert-Manager by default, since 3. disables integrated acme anyway so it will be used by both traefik and ingress-nginx.
5. Even if Longhorn isn't enabled, installs required packages so it can be added easily after cluster creation.
6. Added `cifs-utils` to default packages.
7. **FIXED CHECK FOR `IP` WHEN USING LB_HOSTNAME**
8. Moved both ingresses to their namespaces respectively.
9. Removed outbound rules which cause more issues than good.
10. Added `replicas` vars for both ingress-nginx and traefik which is by default 3 for both.
11. Added kured `start_time`, `end_time` and `time_zone` which default to 3AM, 8AM and Local respectively.

2023-01-18 11:14 UTC, mysticaltech approved these changes

2023-01-18 11:14 UTC, mysticaltech commented on main.tf
> -  # Important when issuing terraform destroy, otherwise the LB will not let the network get deleted
You are right this was useless.

2023-01-18 11:16 UTC, mysticaltech commented
@aleksasiriski Pretty good work there! Thanks.

@ifeulner @captnCC, can you have a look folks, he cleaned up a good amount of obsolete logic.

2023-01-18 11:27 UTC, aleksasiriski commented on main.tf
> -  # Important when issuing terraform destroy, otherwise the LB will not let the network get deleted
Actually I think it was necessary when using k3s integrated Traefik, but since I switched to helm chart for traefik it gets deleted with the code above which deletes the kustomize (all helm charts)

2023-01-18 11:34 UTC, aleksasiriski commented
Why is IPv6 failing? I just tried it on my cluster and it changed the firewall correctly. Also it was literally copied from the example config.

2023-01-19 10:01 UTC, mysticaltech commented
@aleksasiriski We never had support for IPv6. It's just supported to reach the LB because Hetzner also gives IPv6 addresses.

2023-01-19 10:04 UTC, mysticaltech commented
And for the failing checks, please use `terraform format` and `terraform validate` to make sure it passes.

2023-01-19 12:03 UTC, captnCC requested changes
All in all great work! I have left a few minor notes to be addressed.
Since this PR touches a lot of logic, we should test it especially for existing clusters

2023-01-19 12:24 UTC, aleksasiriski commented on variables.tf
> +  default     = "v1.25"
Even 1.26 in using the official chart, idk about rancher's fork:
https://longhorn.io/docs/1.4.0/deploy/important-notes/#supported-kubernetes-versions

2023-01-19 12:26 UTC, aleksasiriski commented on variables.tf
> +  default     = 3
Why would that make any difference for stability or compatibility? Compatibility is already gone since I switched from K3s' integrated Traefik to official Helm Chart, and keeping this below 2 results in dropped packets when Kubernetes is moving the pod.

2023-01-19 12:28 UTC, aleksasiriski commented on templates/traefik_ingress.yaml.tpl
> +  name: traefik
I agree, will make the change. Also I would like to rename "ngx" and "nginx-ingress" occurences to "ingress-nginx" since that's the correct name for the Go implementation of nginx from Kubernetes, whereas "nginx-ingress" is the less popular controller from nginx directly.

2023-01-19 12:32 UTC, aleksasiriski commented on main.tf
> -  provisioner "local-exec" {
But it is deleted? If you mean that part with traefik, I didn't even think about deleting other parts.

2023-01-19 12:32 UTC, aleksasiriski commented on docs/terraform.md
> +| <a name="input_kured_options"></a> [kured\_options](#input\_kured\_options) | n/a | `map(string)` | `{}` | no |
Will do

2023-01-19 13:32 UTC, ifeulner commented on variables.tf
> +  default     = "v1.25"
Yes, meanwhile longhorn 1.4.0 is release, and this supports K8s 1.25 finally.

2023-01-19 16:05 UTC, mysticaltech commented on templates/traefik_ingress.yaml.tpl
> +  name: traefik
@aleksasiriski Try it, you will see that "ingress-nginx" already shows up in the service name, so it becomes something along the lines of "ngx-ingress-nginx" less repetition than "ingress-nginx-ingress-nginx" (the name of the helm chart is used in there).

2023-01-19 19:52 UTC, aleksasiriski commented on templates/traefik_ingress.yaml.tpl
> +  name: traefik
> @aleksasiriski Try it, you will see that "*ingress-nginx" already shows up in the service name, so it becomes something along the lines of "ngx-ingress-nginx" less repetition than "ingress-nginx-ingress-nginx" (the name of the helm chart is used in there).

Well then it's OK for it to stay ngx, but I would like to change every nginx-ingress to ingress-nginx since it may be confusing as it currently is.

2023-01-19 21:25 UTC, ifeulner reviewed
good stuff @aleksasiriski but some comments from me

2023-01-19 22:27 UTC, aleksasiriski commented on main.tf
>    depends_on = [
Because I switched to Helm Traefik instead of the K3s integrated one and because it's a external Helm chart like ingress-nginx and Longhorn it gets properly removed with Kustomization file

2023-01-19 22:31 UTC, aleksasiriski commented on main.tf
>    depends_on = [
> Why to have this at all? Maybe we should just support one ingress implementation - nginx. Too many variables otherwise. @mysticaltech what do you think?

I can't comment below for some reason...

I personally prefer Traefik since it's easier to use global middlewares, but for replication to work you can't use the integrated K3s Traefik but the official Helm Chart instead. Also, why would we remove support for it, it's not hard to support both and the code is already here and working..

2023-01-19 22:33 UTC, aleksasiriski commented on locals.tf
> -      ], !local.using_klipper_lb ? [] : [
I'll add an option for people to choose if they want to restrict or allow all outbound traffic. My main problem was that this was hardcoded and I had to manually add rules that allow all traffic which resulted in having 6 outbound rules that essentially just cancel each other out for no reason.

2023-01-19 22:34 UTC, aleksasiriski commented on locals.tf
I'll add an option for other packages as well, but force them of Longhorn is enabled.

2023-01-19 22:36 UTC, aleksasiriski commented on variables.tf
> +  default     = 3
I can revert the check that was used for ingress-nginx replicas and apply if here (if there are a certain number of nodes, use 2 replicas, etc.)

2023-01-19 23:08 UTC, aleksasiriski commented on variables.tf
> +  default     = 3
> Why to have this at all? Maybe we should just support one ingress implementation - nginx. Too many variables otherwise. @mysticaltech what do you think?

I personally prefer Traefik since it's easier to use global middlewares, but for replication to work you can't use the integrated K3s Traefik but the official Helm Chart instead. Also, why would we remove support for it, it's not hard to support both and the code is already here and working..

2023-01-19 23:24 UTC, aleksasiriski commented on docs/terraform.md
> +| <a name="input_kured_options"></a> [kured\_options](#input\_kured\_options) | n/a | `map(string)` | `{}` | no |
I'll leave this to the bot if/when this gets merged...

2023-01-19 23:26 UTC, aleksasiriski commented on templates/traefik_ingress.yaml.tpl
> +  name: traefik
I believe I found a good middleground that isn't confusing and is consistent. It's commited.

2023-01-19 23:33 UTC, aleksasiriski commented
I revamped the first comment mentioning all the changes, making it more readable as well as updating what has changed and sorting it.

2023-01-20 00:21 UTC, otavio commented on main.tf
>    depends_on = [
We also do this here. However, in our case, we do that externally by installing it from `fluxcd.`

2023-01-20 00:26 UTC, otavio approved these changes

2023-01-20 08:30 UTC, ifeulner approved these changes

2023-01-20 10:44 UTC, captnCC commented on main.tf
>    depends_on = [
@ifeulner This line didn't work for a long time since the kubeconfig name changed anyway. Additionally it would only work under a set of circumstances anyway: `kubectl` must be installed, the kubeconfig must exist from a before apply (which can be disabled and doesn't work in CI systems)

2023-01-20 11:59 UTC, aleksasiriski commented
Also, if longhorn has the default number of replicas 3, why wouldn't that be default for traefik and nginx as well?

2023-01-20 13:09 UTC, captnCC requested changes
I've done a test to upgrade from the current `master`-branch to the PR branch. Seems to far to go without breaking changes. (I didn't test for longhorn itself).

Yet none of the changes to ingress or anything will be applied to the cluster. 
Should we just go with it letting the existing config be untouched or should we make sure that the changes from the module upgrade will we applied? @mysticaltech @ifeulner

2023-01-20 13:09 UTC, captnCC commented on locals.tf
> +        destination_ips = ["0.0.0.0/0", "::/0"]
It's a weirdness in terraform but no the `icmp` fails the validation:
```
╷
│ Error: Inconsistent conditional result types
│ 
│   on locals.tf line 146, in locals:
│  146:     ], !var.restrict_outbound_traffic ? [] : [
│  147:     # Allow basic out traffic
│  148:     # ICMP to ping outside services
│  149:     {
│  150:       direction       = "out"
│  151:       protocol        = "icmp"
│  152:       destination_ips = ["0.0.0.0/0", "::/0"]
│  153:     },
│  154:     # DNS
│  155:     {
│  156:       direction       = "out"
│  157:       protocol        = "tcp"
│  158:       port            = "53"
│  159:       destination_ips = ["0.0.0.0/0", "::/0"]
│  160:     },
│  161:     {
│  162:       direction       = "out"
│  163:       protocol        = "udp"
│  164:       port            = "53"
│  165:       destination_ips = ["0.0.0.0/0", "::/0"]
│  166:     },
│  167:     # HTTP(s)
│  168:     {
│  169:       direction       = "out"
│  170:       protocol        = "tcp"
│  171:       port            = "80"
│  172:       destination_ips = ["0.0.0.0/0", "::/0"]
│  173:     },
│  174:     {
│  175:       direction       = "out"
│  176:       protocol        = "tcp"
│  177:       port            = "443"
│  178:       destination_ips = ["0.0.0.0/0", "::/0"]
│  179:     },
│  180:     #NTP
│  181:     {
│  182:       direction       = "out"
│  183:       protocol        = "udp"
│  184:       port            = "123"
│  185:       destination_ips = ["0.0.0.0/0", "::/0"]
│  186:     }
│  187:     ], !local.using_klipper_lb ? [] : [
│     ├────────────────
│     │ var.restrict_outbound_traffic is a bool
│ 
│ The true and false result expressions must have consistent types. The 'true' tuple has length 0, but the 'false' tuple has length 6.
```
The ports needs to be defined anyway for terraform

2023-01-20 13:09 UTC, captnCC commented on variables.tf
> +  }
The default should be `1` instead of `null` (as the variable isn't flagged as nullable). Then the validation can be shortened to just `var.traefik_replica_count > 0`

2023-01-20 13:09 UTC, captnCC commented on variables.tf
> +  }
The default should be `1` instead of `null` (as the variable isn't flagged as nullable). Then the validation can be shortened to just `var.nginx_replica_count > 0`

2023-01-20 13:14 UTC, aleksasiriski commented on variables.tf
> +  }
Then the code for node count won't ever be activated. Why do you insist so much that is should be 1 and not 3 or 2? Longhorn has 3 for default...

2023-01-20 13:17 UTC, aleksasiriski commented on locals.tf
> +        destination_ips = ["0.0.0.0/0", "::/0"]
Why? It's identical to ```], !local.using_klipper_lb ? [] : [```

2023-01-20 13:17 UTC, captnCC commented on variables.tf
> +  }
It's not about the number itself, just that with default = null the config is broken. So either the variable should be flagged as nullable or the default needs to be changed

2023-01-20 13:18 UTC, aleksasiriski commented on variables.tf
> +  }
I just removed the replica count and set it to autodetect based on number of agents. It doesn't make sense to be 1 by default and 3 can be overkill for smaller setups.

2023-01-20 13:19 UTC, captnCC commented on locals.tf
> +        destination_ips = ["0.0.0.0/0", "::/0"]
It seems to be a quirk of terraform and the short hand if. So all objects of the array need to have the same form. It played around and found that adding the port fixed it magically

2023-01-20 13:58 UTC, aleksasiriski commented on variables.tf
> +  }
Fixed.

2023-01-20 13:58 UTC, aleksasiriski commented on variables.tf
> +  }
Fixed.

2023-01-20 14:19 UTC, aleksasiriski commented on locals.tf
> +        destination_ips = ["0.0.0.0/0", "::/0"]
Adding ```port            = ""``` fixed terraform warnings?

2023-01-20 14:30 UTC, mysticaltech commented on locals.tf
> +        destination_ips = ["0.0.0.0/0", "::/0"]
@captnCC Something seems indeed wrong with `var.restrict_outbound_traffic`, as the error message about says "The 'true' tuple has length 0, but the 'false' tuple has length 6".

2023-01-20 14:33 UTC, mysticaltech commented on variables.tf
> +  }
@aleksasiriski @captnCC If there is one node in the cluster, it cannot be 3 anyways. So we need to use smart logic here. 1 is total agent counts < 3, and 3 if total agent counts >=3. The nodes counts are already computed in local.tf, so that can be reused.

2023-01-20 14:35 UTC, mysticaltech commented on variables.tf
> +  }
> I've done a test to upgrade from the current `master`-branch to the PR branch. Seems to far to go without breaking changes. (I didn't test for longhorn itself).
> 
> Yet none of the changes to ingress or anything will be applied to the cluster. Should we just go with it letting the existing config be untouched or should we make sure that the changes from the module upgrade will we applied? @mysticaltech @ifeulner

@captnCC I need we can just release it under a minor next version so 1.8, it's not big breaking changes, and as you said, the main changes will not get applied anyways.

2023-01-20 14:38 UTC, mysticaltech commented on locals.tf
> +        destination_ips = ["0.0.0.0/0", "::/0"]
@aleksasiriski Yes it needs to be the same format, as the inside logic relies on it for merging.

2023-01-20 14:51 UTC, mysticaltech commented on variables.tf
> +  default     = 3
@ifeulner IMHO we can keep both, as they will work the same, and the logic is there already. They are the two most common ingress controllers for Kube, and supporting both insures we appeal to the max audience!

2023-01-20 14:53 UTC, aleksasiriski commented on locals.tf
> +        destination_ips = ["0.0.0.0/0", "::/0"]
Ok, it's fixed now. I also took the liberty of correcting grammar and updating info in the example file.

2023-01-20 14:54 UTC, mysticaltech commented on locals.tf
We already have an option for extra packages, so @aleksasiriski if cifs is not often used like @ifeulner says, we can just remove it, and people that needs it can use the `extra_packages_to_install` variable.

2023-01-20 15:28 UTC, captnCC approved these changes
From my perspective it look good now!

2023-01-20 18:32 UTC, aleksasiriski commented
Also switched to markdown's auto incrementing when using an ordered list.

2023-01-21 09:53 UTC, mysticaltech requested changes

2023-01-21 09:53 UTC, mysticaltech commented on README.md
> +1. Generate a passphrase-less ed25519 SSH key pair for your cluster; take note of the respective paths of your private and public keys. Or, see our detailed [SSH options](https://github.com/kube-hetz
@aleksasiriski FYI, look at the numbers.

2023-01-21 09:53 UTC, mysticaltech commented on README.md
> +1. Create your Branch (`git checkout -b AmazingFeature`)
@aleksasiriski Same here for the numbered list.

2023-01-21 09:53 UTC, mysticaltech commented on locals.tf
> +    "start-time": "${var.kured_start_time}",
@aleksasiriski Please remove these time constraints for the default case. The reason for that is that for a huge cluster, the way it is configured now, it will automatically reboot 1 node at a time, and will spread it in time as long as needed.

Also, most cluster operations are not contained to any local times, so just best to remove that constraint by default IMHO.

2023-01-21 09:53 UTC, mysticaltech commented on variables.tf
> +variable "kured_start_time" {
@aleksasiriski See the comment above, about the default.

2023-01-21 09:53 UTC, mysticaltech commented on README.md
> +Per default a node that installed updates will reboot between 3AM and 8AM Local time, and updates are installed roughly every 24 hours.
@aleksasiriski See my comment below, I would really prefer that to stay the same as before by default, though adding the possibility to customize is great.

2023-01-21 10:01 UTC, mysticaltech commented
@aleksasiriski Keep up the good work! After the above comments are handled, I'll give it one last check and if all good, will do a test deploy, and when that passes, we will merge and release 1.8 🙏

2023-01-21 10:03 UTC, mysticaltech commented on README.md
> +Per default a node that installed updates will reboot between 3AM and 8AM Local time, and updates are installed roughly every 24 hours.
And about the detailed options below, best to include them in kube.tf instead, and commented, so folks can just uncomment them if they want to use it. And it will also make the Readme clearer by removing everything that can live in the Kube.tf file instead.

2023-01-21 11:38 UTC, aleksasiriski commented on README.md
> +1. Generate a passphrase-less ed25519 SSH key pair for your cluster; take note of the respective paths of your private and public keys. Or, see our detailed [SSH options](https://github.com/kube-hetz
It's autoincrementing when everything is 1. It's a markdown feature!

2023-01-21 11:38 UTC, aleksasiriski commented on README.md
> +1. Create your Branch (`git checkout -b AmazingFeature`)
It's autoincrementing when everything is 1. It's a markdown feature!

2023-01-21 11:39 UTC, aleksasiriski commented on locals.tf
> +    "start-time": "${var.kured_start_time}",
Will do!

2023-01-21 11:39 UTC, aleksasiriski commented on README.md
> +Per default a node that installed updates will reboot between 3AM and 8AM Local time, and updates are installed roughly every 24 hours.
Alright.

2023-01-21 11:55 UTC, aleksasiriski commented on README.md
> +1. Generate a passphrase-less ed25519 SSH key pair for your cluster; take note of the respective paths of your private and public keys. Or, see our detailed [SSH options](https://github.com/kube-hetz
You can see [here](https://github.com/aleksasiriski/k3s-on-hetzner/blob/master/README.md) that it's working properly.

2023-01-21 11:56 UTC, aleksasiriski commented on README.md
> +1. Create your Branch (`git checkout -b AmazingFeature`)
Above comment.

2023-01-21 12:03 UTC, aleksasiriski commented
I suggest reading the first comment once more, I've updated it with all the changes.

2023-01-21 22:20 UTC, aleksasiriski commented
I just made a new cluster and it works flawlessly, here's the config:

```terraform
locals {
  hcloud_token = "woohoo"
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = local.hcloud_token

  source = "github.com/aleksasiriski/k3s-on-hetzner"
  ssh_public_key = file("~/.ssh/id_rsa.pub")
  ssh_private_key = file("~/.ssh/id_rsa")

  control_plane_nodepools = [
    {
      name        = "control-plane-nbg1",
      server_type = "cpx11",
      location    = "nbg1",
      labels      = [
        "node.kubernetes.io/server-usage=master",
        "node.kubernetes.io/server-location=nbg1",
        "node.kubernetes.io/server-country=ger"
      ],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [
        "node.kubernetes.io/server-usage=master",
        "node.kubernetes.io/server-location=fsn1",
        "node.kubernetes.io/server-country=ger"
      ],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-hel1",
      server_type = "cpx11",
      location    = "hel1",
      labels      = [
        "node.kubernetes.io/server-usage=master",
        "node.kubernetes.io/server-location=hel1",
        "node.kubernetes.io/server-country=fin"
      ],
      taints      = [],
      count       = 1
    }
  ]

  agent_nodepools = [
    {
      name        = "agent-main-nbg1",
      server_type = "cpx21",
      location    = "nbg1",
      labels      = [
        "node.kubernetes.io/server-usage=main",
        "node.kubernetes.io/server-location=nbg1",
        "node.kubernetes.io/server-country=ger"
      ],
      taints      = [],
      count       = 1
    },
    {
      name        = "agent-main-fsn1",
      server_type = "cpx21",
      location    = "fsn1",
      labels      = [
        "node.kubernetes.io/server-usage=main",
        "node.kubernetes.io/server-location=fsn1",
        "node.kubernetes.io/server-country=ger"
      ],
      taints      = [],
      count       = 1
    }
  ]

  cluster_name = "example"
  base_domain = "cluster.example.com"
  lb_hostname = "ingress.example.com"
  extra_packages_to_install = ["nfs-client", "cifs-utils"]
  restrict_outbound_traffic = false
  ingress_replica_count = 3

  kured_options = {
    "start-time": "03:00"
    "end-time": "08:00"
    "time-zone": "Local"
  }

}

provider "hcloud" {
  token = local.hcloud_token
}

terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.35.2"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}
```

2023-01-22 15:44 UTC, captnCC commented
@aleksasiriski Now just the formatting needs to be fixed with `terraform fmt -recursive`, then this should be ready to merge! 🎉

2023-01-23 07:12 UTC, mysticaltech requested changes
@aleksasiriski Almost perfect. Please just address the point above and we're good to go!

2023-01-23 07:12 UTC, mysticaltech commented on variables.tf
> +  default     = "https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2"
@aleksasiriski Please revert that. We have chosen that mirror for because the main link gave mirrors that had blacklisted hetzner servers. But the default one we have is working great!

2023-01-23 07:26 UTC, aleksasiriski commented on variables.tf
> +  default     = "https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2"
The default one downloads at 300Kbps for me, but OK I'll revert it.. There are also other mirrors available that are much faster

2023-01-23 07:36 UTC, mysticaltech commented on variables.tf
> +  default     = "https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2"
Yes, but it depends on people's locations. At least this one works well for most people. It's been several months now with no issues. But anyways, you can customize the link by setting the variable.

2023-01-23 10:34 UTC, aleksasiriski commented on variables.tf
> +  default     = "https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2"
It only depends on Hetzner VPS location, and this mirror is fixated in DE which in turn means across the seas connection for VPSs in USA, and even though it's in DE a DE VPS gets only 300KB/s whereas the official mirror or for example [this one](https://mirror.dogado.de/opensuse/tumbleweed/appliances/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2) gets 1MB/s.

Testing on my own home connection, the old mirror gives around 40MB/s and both the official and dogado DE max out my connection at 60MB/s.

2023-01-23 13:47 UTC, mysticaltech commented
@aleksasiriski Thank you for this, it's a great contribution. I will give it a quick deploy, and if all good. It will be released tonight CET under 1.8.0 🚀

2023-01-23 13:47 UTC, mysticaltech approved these changes

2023-01-23 21:40 UTC, merged

2023-01-23 21:49 UTC, mysticaltech commented
Deployed! 🙏 🚀