Drop default ssh firewall rule when custom ssh port is used
kube-hetzner/terraform-hcloud-kube-hetzner pull request #844
Opened 2023-06-15 06:09 UTC by MaximilianMeister

It is not necessary to open the standard port 22 when using a custom port

2023-06-15 13:48 UTC, aleksasiriski commented
Have you tested building a complete cluster from scratch with this patch? I forgot if nodes are firstly added to the firewall and only afterwards the port is changed from the default, which would make this patch break the cluster setup or if it was the other way around, which means it's perfectly safe to merge this patch.

2023-06-15 19:37 UTC, MaximilianMeister commented
@aleksasiriski Yeah, I tested it with a 3 CP + 2 Worker node cluster and checked the firewall by looking into hetzner UI and also trying to ssh into a machine and it seems to do the trick

2023-06-15 19:41 UTC, aleksasiriski requested changes

2023-06-15 19:41 UTC, aleksasiriski commented on locals.tf
> +    # Allow all traffic to the ssh port
Please combine this into a single rule, there's no need for checking if the port is 22, just set it to `var.ssh_port` since it has the default value of 22 if nothing is set in kube.tf.

2023-06-15 19:58 UTC, aleksasiriski approved these changes

2023-06-16 01:57 UTC, mysticaltech commented
@MaximilianMeister Indeed that is legacy logic left over from the days when we used to enter rescue mode to install the OS. Thanks for the find!

2023-06-16 04:11 UTC, mysticaltech approved these changes

2023-06-16 04:11 UTC, merged

2023-06-16 04:44 UTC, MaximilianMeister commented
> Indeed that is legacy logic left over from the days when we used to enter rescue mode to install the OS. Thanks for the find!

Ah good to know. Thanks!