Fix name for control-lb + prevent infinite waiting when using lb_host…
kube-hetzner/terraform-hcloud-kube-hetzner pull request #908
Opened 2023-07-26 16:48 UTC by mnbro

1. Correlates '"hcloud_load_balancer" "cluster"' name between control_planes.tf and data.tf
2. When using lb_hostname="some.fqdn" terraform is stuck in 'Waiting for load-balancer to get an IP...', this is because `kubectl get -n traefik service/traefik --output=jsonpath='{.status.loadBalancer.ingress[0]}'`
return only `{"ip":"1.1.1.1"}`

2023-07-27 10:17 UTC, aleksasiriski requested changes

2023-07-27 10:17 UTC, aleksasiriski commented on init.tf
> +      until [ -n "\$(kubectl get -n ${lookup(local.ingress_controller_namespace_names, local.ingress_controller)} service/${lookup(local.ingress_controller_service_names, local.ingress_controller)} -
If you use the option `lb_hostname` this will hang. This should be reverted (I fixed it a long time ago).

Is anyone even using a control plane lb for kubectl / ssh (if it's even configured to work with ssh)? @mysticaltech

2023-07-27 10:20 UTC, aleksasiriski approved these changes

2023-07-30 02:55 UTC, mysticaltech approved these changes

2023-07-30 02:56 UTC, mysticaltech commented
@mnbro Thanks for this fix! I wonder how the old logic ended up this way 🤦🏻

2023-07-30 02:56 UTC, merged

2023-07-30 03:57 UTC, mysticaltech commented
@mnbro Had to revert the change for the lb name in data.tf as it did not deploy and was not backward compatible, I missed it in the review, the rest was ok. Thanks for the main hanging fix and no worries!

2023-08-01 04:29 UTC, mysticaltech commented
@mnbro Yes, it's because you had changed it. You could try renaming it manually to k3s over at Hetzner. Also make sure to set the cluster variable.

2023-08-01 17:16 UTC, mysticaltech commented
Anyways, that change would break backward compatibility. On top of that, this lb is not associated with the control planes. There's another one for that.